### ISSUE TITLE
colqwen2.5-v0.2 evaluation vidore-v2 issue

### ISSUE THREAD

**Issue by StupidBuluchacha** [illuin-tech/vidore-benchmark#117]
I ran the following script but got error.
`vidore-benchmark evaluate-retriever \
    --model-class colqwen2 \
    --model-name vidore/colqwen2.5-v0.2 \
    --collection-name vidore/vidore-benchmark-v2-67ae03e3924e85b36e7f53b0 \
    --dataset-format beir \
    --split test`

I have successfully got the result of vidore/colpali-v1.3 using similar script structure. but vidore/colqwen2.5-v0.2 got the following error.
`RuntimeError: Error(s) in loading state_dict for Linear:
        size mismatch for bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).`

I am using vidore-benchmark 5.0.0. Look forward to help. Thanks! @ManuelFay @tonywu71

**Comment by ManuelFay** [comment]
Argh not sure we merged actually !
But yeah ColQwen25 is not the same as ColQwen2, there might be a branch, we will try to merge this in.

FYI, we now recommend evaluating with MTEB rather than this repo

**Comment by QuentinJGMace** [comment]
Hey @StupidBuluchacha, should be good now you should be able to run
`vidore-benchmark evaluate-retriever \ --model-class colqwen2_5 \ --model-name vidore/colqwen2.5-v0.2 \ --collection-name vidore/vidore-benchmark-v2-67ae03e3924e85b36e7f53b0 \ --dataset-format beir \ --split test`

Tell me if anything is needed

**Comment by StupidBuluchacha** [comment]
> Hey [@StupidBuluchacha](https://github.com/StupidBuluchacha), should be good now you should be able to run `vidore-benchmark evaluate-retriever \ --model-class colqwen2_5 \ --model-name vidore/colqwen2.5-v0.2 \ --collection-name vidore/vidore-benchmark-v2-67ae03e3924e85b36e7f53b0 \ --dataset-format beir \ --split test`
> 
> Tell me if anything is needed

Hi @QuentinJGMace , I run `vidore-benchmark evaluate-retriever \ --model-class colqwen2_5 \ --model-name vidore/colqwen2.5-v0.2 \ --collection-name vidore/vidore-benchmark-v2-67ae03e3924e85b36e7f53b0 \ --dataset-format beir \ --split test`, but it gets 

> ValueError: Unknown model name `colqwen25`. Available models: ['bge-m3-colbert', 'bge-m3', 'biqwen2', 'bm25', 'cohere', 'colidefics3', 'colpali', 'colqwen2', 'dse-qwen2', 'dummy_vision_retriever', 'jina-clip-v1', 'nomic-embed-vision', 'siglip']

So I think colqwen25 is still not working yet, and I am using vidore-benchmark 5.0.0. Can you double-check this issue? Thx!
